/*
  ==============================================================================

    This file was auto-generated by the Introjucer!

    It contains the basic framework code for a JUCE plugin editor.

  ==============================================================================
*/

#include "PluginProcessor.h"
#include "PluginEditor.h"


//==============================================================================
DiauproPluginAudioProcessorEditor::DiauproPluginAudioProcessorEditor (DiauproPluginAudioProcessor& p)
    :  AudioProcessorEditor (&p),ready(false), processor (p)
{

    // Make sure that before the constructor has finished, you've set the
    // editor's size to whatever you need it to be.
    addAndMakeVisible(gui = new DiauproGUI());
    setSize (800, 800);
    this->inst = this;
}

DiauproPluginAudioProcessorEditor::~DiauproPluginAudioProcessorEditor()
{
    this->inst = NULL;
}

//==============================================================================
void DiauproPluginAudioProcessorEditor::paint (Graphics& g)
{
    gui->setVcoTime(processor.vcoProcessTime, processor.vcoRtTime, processor.vcoRtMaxTime, processor.vcoRtMinTime);
    gui->setVcoNetStatus(processor.vcoNetStatus);
    gui->setVcaTime(processor.vcaProcessTime, processor.vcaRtTime, processor.vcaRtMaxTime, processor.vcaRtMinTime);
    gui->setVcaNetStatus(processor.vcaNetStatus);
    gui->setNullTime(processor.nullProcessTime, processor.nullRtTime, processor.nullRtMaxTime, processor.nullRtMinTime);
    gui->setNullNetStatus(processor.nullNetStatus);
    g.fillAll (Colours::white);

    g.setColour (Colours::black);
    g.setFont (15.0f);
    g.drawFittedText ("Hello World!", getLocalBounds(), Justification::centred, 1);
    ready = true;
}

void DiauproPluginAudioProcessorEditor::resized()
{
    // This is generally where you'll want to lay out the positions of any
    gui->setSize(getWidth(), getHeight());
    // subcomponents in your editor..
}

bool DiauproPluginAudioProcessorEditor::isReady()
{
    if (this != this->inst) {
        return false;
    }
    return ready;
}
